[[redirects]]
  from = "/proxy/*"
  to = "https://wantedtodoapp.netlify.app/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "https://pre-onboarding-selection-task.shop/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200